### ISSUE TITLE
Point might need to support float type

### ISSUE THREAD

**Issue by tjb1982** [tebeka/selenium#85] opened 2017-06-30 16:08 UTC
I noticed today that WebElement.Location() seems to be returning a float now instead of an int, and the json decoder doesn't convert them into ints. It's hard to understand why Selenium would ever return a float for this (should be pixels, right?) but it's definitely breaking my tests today and it wasn't yesterday. I'm using Selenium via browserstack, so there's not a lot I can do to configure this as I understand it.

Also, as a rule I don't think json supports `int`, only `Number` as it's based on javascript, so anything being (un)marshaled should probably support float instead?

**Comment by minusnine** [comment] 2017-06-30 17:18
Sorry for the breakage. The culprit is b534f367abc9.

What browser version and Selenium version are you running? If Firefox and Selenium > 3, what version of Geckodriver are you using?

**Comment by tjb1982** [comment] 2017-06-30 17:26
Thanks for getting back so quickly. The browser version is Chrome 59.0.3071.86 running on Windows NT with chromedriver version 2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41). I can't find the Selenium server version they're using, oddly.

**Comment by tjb1982** [comment] 2017-06-30 17:28
I don't really see how that commit broke this, but for right now I've forked this repo and modified the Point struct to take `float32` and we're using that for the time being: https://github.com/nclk/selenium/commit/45d5403886d412888316bdd3fb94e304c02ff7e1

**Comment by tjb1982** [comment] 2017-06-30 17:33
According to [this page](https://www.browserstack.com/automate/capabilities), the default Se version is 2.53.0.

**Comment by minusnine** [comment] 2017-06-30 17:41
Thanks for the information. I don't understand how changing the API types affects parsing, as we parse the WebDriver output using a float32 and then do a type conversion later.

Can you call "selenium.SetDebug(true)" in your test and provide the resulting output here? Specifically, I'm looking for the lines like:

```
2017/06/30 17:34:33 -> GET http://127.0.0.1:33478/wd/hub/session/68042217-c965-4036-a0ea-5ada6b88ca93/element/0/location

2017/06/30 17:34:33 <- 200 OK [[application/json;charset=utf-8]]
{                                                  
    "state": "success",
    "sessionId": "68042217-c965-4036-a0ea-5ada6b88ca93",                                                 
    "hCode": 597152736,                                                                                 
    "value": {                  
        "x": 5,                                                 
        "y": 5,
        "hCode": 655360,
        "class": "org.openqa.selenium.Point"            
    },                  
    "class": "org.openqa.selenium.remote.Response",
    "status": 0                                    
}    
```

I'm having trouble reproducing the problem.

**Comment by minusnine** [comment] 2017-06-30 17:57
Ignore the above commit. I don't understand why that combination of Selenium+Chrome is getting into the codepath that you modified in nclk/selenium@45d5403 to fix your problem, so the issue is different from that commit.

I'll rejigger the test setup to use exactly the versions you are using.

The one rub is that I'm on vacation from tonight until Tuesday. :-(

**Comment by tjb1982** [comment] 2017-06-30 18:03
[foo.txt](https://github.com/tebeka/selenium/files/1116115/foo.txt)

That's output from the whole run. This is what I'm seeing: 

```javascript
2017/06/30 13:56:15 -> GET http://hub-cloud.browserstack.com/wd/hub/session/eb1764dc2a5f3a2cc66c20f1f119cd3c3266b7e6/element/0.49547198085717237-1/location

2017/06/30 13:56:15 <- 200 OK [[application/json; charset=utf-8]]
{
    "sessionId": "eb1764dc2a5f3a2cc66c20f1f119cd3c3266b7e6",
    "status": 0,
    "value": {
        "ceil": {},
        "clone": {},
        "floor": {},
        "round": {},
        "scale": {},
        "toString": {},
        "translate": {},
        "x": 19.15625,
        "y": 216.59375
    }
}

```

**Comment by tjb1982** [comment] 2017-06-30 18:12
From where I'm standing, it seems that sometimes the values that come from the driver are floating point, and I suspect they feel free to do that because JSON doesn't distinguish between int and float, etc. like I was saying in my original comment. So I think it might just be a good idea to assume that you might get a float from anything you have to deserialize; e.g., here https://github.com/nclk/selenium/blob/45d5403886d412888316bdd3fb94e304c02ff7e1/remote.go#L1262 because this appears to be where the error is occurring.

**Comment by minusnine** [comment] 2017-07-18 16:30
I apologize for my tardiness on this issue.

I just committed the above potential fix: handle the incoming JSON with floats, and then emit a rounded value from the API. This makes the fix API-compatible and similar to other existing APIs.

Can you pull from HEAD and test? Thank you in advance.

**Comment by tjb1982** [comment] 2017-07-20 16:11
Thank for the update. I'll test it out as soon as I can and get back to you.

**Comment by minusnine** [comment] 2017-08-22 15:34
Thanks again for the bug report. Please reopen if this is not fixed.

**Closed by minusnine** 2017-08-22 15:34 UTC
